name: "hardkees"
url: "https://hardkees.me/"

baseurl: "https://hardkees.me"

cats:
 - news
 - technology
 - Vulns and exploits

relative_permalinks: false
permalink: ":year:month:day-:title.html"

markdown: kramdown
kramdown:
  hard_wrap: false
  entity_output: "symbolic"
  line_width: 68

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
